twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
      categorieRepository: "@App\\Repository\\CategoryRepository"
      cartService: "@App\\Service\\CartService"

when@test:
    twig:
        strict_variables: true
