<?php

namespace ContainerXIEBQMm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XGMTXROService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XGMTXRO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XGMTXRO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'CustomerRepository' => ['privates', 'App\\Repository\\CustomerRepository', 'getCustomerRepositoryService', true],
        ], [
            'CustomerRepository' => 'App\\Repository\\CustomerRepository',
        ]);
    }
}
