<?php

namespace ContainerXIEBQMm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendarViewEmailSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventDispatcher\CalendarViewEmailSubscriber' shared autowired service.
     *
     * @return \App\EventDispatcher\CalendarViewEmailSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventDispatcher'.\DIRECTORY_SEPARATOR.'CalendarViewEmailSubscriber.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\EventDispatcher\\CalendarViewEmailSubscriber'])) {
            return $container->privates['App\\EventDispatcher\\CalendarViewEmailSubscriber'];
        }

        return $container->privates['App\\EventDispatcher\\CalendarViewEmailSubscriber'] = new \App\EventDispatcher\CalendarViewEmailSubscriber(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), $a);
    }
}
