<?php

namespace ContainerXIEBQMm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendar3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kh.3Agn.App\Entity\Calendar' shared service.
     *
     * @return \App\Entity\Calendar
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.kh.3Agn": it references class "App\\Entity\\Calendar" but no such service exists.');
    }
}
