<?php

namespace ContainerCjvFfm5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9AQBoBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9A_qBoB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9A_qBoB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'PurchaseItemRepository' => ['privates', 'App\\Repository\\PurchaseItemRepository', 'getPurchaseItemRepositoryService', true],
            'calendar' => ['privates', '.errored..service_locator.9A_qBoB.App\\Entity\\Calendar', NULL, 'Cannot autowire service ".service_locator.9A_qBoB": it references class "App\\Entity\\Calendar" but no such service exists.'],
            'calendarRepository' => ['privates', 'App\\Repository\\CalendarRepository', 'getCalendarRepositoryService', false],
            'customerRepository' => ['privates', 'App\\Repository\\CustomerRepository', 'getCustomerRepositoryService', true],
        ], [
            'PurchaseItemRepository' => 'App\\Repository\\PurchaseItemRepository',
            'calendar' => 'App\\Entity\\Calendar',
            'calendarRepository' => 'App\\Repository\\CalendarRepository',
            'customerRepository' => 'App\\Repository\\CustomerRepository',
        ]);
    }
}
