<?php

namespace ContainerCjvFfm5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendar2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.J5ClqNV.App\Entity\Calendar' shared service.
     *
     * @return \App\Entity\Calendar
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.J5ClqNV": it references class "App\\Entity\\Calendar" but no such service exists.');
    }
}
