<?php

namespace ContainerCjvFfm5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VaFcGWn.App\Entity\Customer' shared service.
     *
     * @return \App\Entity\Customer
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.VaFcGWn": it references class "App\\Entity\\Customer" but no such service exists.');
    }
}
