<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXIEBQMm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXIEBQMm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXIEBQMm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXIEBQMm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXIEBQMm\App_KernelDevDebugContainer([
    'container.build_hash' => 'XIEBQMm',
    'container.build_id' => '9d8d995a',
    'container.build_time' => 1686904931,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXIEBQMm');
